"""empty message

Revision ID: 966d9ff3131f
Revises: e34abba596cf
Create Date: 2023-06-10 01:51:33.850379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966d9ff3131f'
down_revision = 'e34abba596cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
