"""Initial migration

Revision ID: e34abba596cf
Revises: 
Create Date: 2023-06-08 09:47:29.585282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e34abba596cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('car_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_data', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('camera_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('car_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('car_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ideal_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('violation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plate_number'], ['car.plate_number'], name='car_state_plate_number_fkey'),
    sa.PrimaryKeyConstraint('id', name='car_state_pkey')
    )
    op.create_table('car',
    sa.Column('plate_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('visits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('plate_number', name='car_pkey')
    )
    # ### end Alembic commands ###
